package commands

import "core:flags"
import "core:fmt"
import "core:os"

import "../shared"

ARK_ITEMS :: [?]string{"bin", "build", "tmp", "repos"}

init_ark :: proc(ark_dir: string, options: []string) {
	// Make all .ark dirs
	for folder in ARK_ITEMS {
		ark_sub_dir, _ := os.join_path({ark_dir, folder}, context.allocator)
		// If the folder doesnt exist, make it
		if !shared.check_file_or_folder_exists(ark_sub_dir) { 
			os.make_directory_all(ark_sub_dir)
		}
	}
	
		ark_lock, _ := os.join_path({ark_dir, "ark.lock"}, context.allocator)
	defer delete(ark_lock)
	
	// Create ark.lock
	if !shared.check_file_or_folder_exists(ark_lock) {
		err := os.write_entire_file_from_string(ark_lock, "# Do not edit. File is generated by ark package manager.\n")
		if err != nil {
			fmt.println("ERROR: Failed to initialize ark.lock file:")
			os.exit(1)
		}
	}

	// TODO: If ark.json doesnt exist, make the file with empty json + $schema
	// TODO: Make the json schema for IDEs. Add it to the local dir and point the $schema at it.

	return
}

add_ark_to_path :: proc() {
	// Print out OS specific command to add executable to user path
}
